### ISSUE TITLE
Error when using M5.

### ISSUE THREAD

**Issue by wpoosanguansit** [47deg/scala-android#41]
I do get the errors below when I updated the version from

2.0.0-20150427

to 

2.0.0-M5

[error] /Users/anony/Desktop/Projects/Scala/scala-android/src/main/scala/com/fortysevendeg/scala/android/ui/akkasimon/Layout.scala:25: not found: type IdGeneration
[error]   with IdGeneration
[error]        ^
[error] /Users/anony/Desktop/Projects/Scala/scala-android/src/main/scala/com/fortysevendeg/scala/android/ui/akkasimon/Layout.scala:40: not found: value getUi
[error]              managerContext: FragmentManagerContext[Fragment, FragmentManager]) = getUi(
[error]                                                                                   ^
[error] /Users/anony/Desktop/Projects/Scala/scala-android/src/main/scala/com/fortysevendeg/scala/android/ui/akkasimon/Layout.scala:58: not found: value Id
[error]         findFragmentById[ComputerFragment](Id.computer) map (_.actor.get ! NewGame)
[error]                                            ^
[error] /Users/anony/Desktop/Projects/Scala/scala-android/src/main/scala/com/fortysevendeg/scala/android/ui/akkasimon/Layout.scala:70: exception during macro expansion: 
[error] scala.MatchError: (macroid.FragmentBuilder.apply[com.fortysevendeg.scala.android.ui.akkasimon.fragments.ColorFragment](macroid.Ui.apply[com.fortysevendeg.scala.android.ui.akkasimon.fragments.ColorFragment]%28new com.fortysevendeg.scala.android.ui.akkasimon.fragments.ColorFragment%28%29%29, new android.os.Bundle%28%29)(context, support.this.Fragment.legacyFragment): macroid.FragmentBuilder[com.fortysevendeg.scala.android.ui.akkasimon.fragments.ColorFragment]) (of class scala.reflect.internal.Trees$Typed)
[error]         at macroid.FragmentBuildingMacros.passImpl(FragmentBuilding.scala:92)
[error]             .pass(colorKey -> Color.GREEN, nameColorKey -> GREEN.toLower)
[error]                  ^
[error] /Users/anony/Desktop/Projects/Scala/scala-android/src/main/scala/com/fortysevendeg/scala/android/ui/akkasimon/Layout.scala:71: not found: value Id
[error]             .framed(Id.green, GREEN.toLower) <~ rowStyle,
[error]                     ^
[error] /Users/anony/Desktop/Projects/Scala/scala-android/src/main/scala/com/fortysevendeg/scala/android/ui/akkasimon/Layout.scala:73: exception during macro expansion: 
[error] scala.MatchError: (macroid.FragmentBuilder.apply[com.fortysevendeg.scala.android.ui.akkasimon.fragments.ColorFragment](macroid.Ui.apply[com.fortysevendeg.scala.android.ui.akkasimon.fragments.ColorFragment]%28new com.fortysevendeg.scala.android.ui.akkasimon.fragments.ColorFragment%28%29%29, new android.os.Bundle%28%29)(context, support.this.Fragment.legacyFragment): macroid.FragmentBuilder[com.fortysevendeg.scala.android.ui.akkasimon.fragments.ColorFragment]) (of class scala.reflect.internal.Trees$Typed)
[error]         at macroid.FragmentBuildingMacros.passImpl(FragmentBuilding.scala:92)
[error]             .pass(colorKey -> Color.RED, nameColorKey -> RED.toLower)
[error]                  ^
[error] /Users/anony/Desktop/Projects/Scala/scala-android/src/main/scala/com/fortysevendeg/scala/android/ui/akkasimon/Layout.scala:74: not found: value Id
[error]             .framed(Id.red, RED.toLower) <~ rowStyle
[error]                     ^
[error] /Users/anony/Desktop/Projects/Scala/scala-android/src/main/scala/com/fortysevendeg/scala/android/ui/akkasimon/Layout.scala:78: exception during macro expansion: 
[error] scala.MatchError: (macroid.FragmentBuilder.apply[com.fortysevendeg.scala.android.ui.akkasimon.fragments.ColorFragment](macroid.Ui.apply[com.fortysevendeg.scala.android.ui.akkasimon.fragments.ColorFragment]%28new com.fortysevendeg.scala.android.ui.akkasimon.fragments.ColorFragment%28%29%29, new android.os.Bundle%28%29)(context, support.this.Fragment.legacyFragment): macroid.FragmentBuilder[com.fortysevendeg.scala.android.ui.akkasimon.fragments.ColorFragment]) (of class scala.reflect.internal.Trees$Typed)
[error]         at macroid.FragmentBuildingMacros.passImpl(FragmentBuilding.scala:92)
[error]             .pass(colorKey -> Color.BLUE, nameColorKey -> BLUE.toLower)
[error]                  ^
[error] /Users/anony/Desktop/Projects/Scala/scala-android/src/main/scala/com/fortysevendeg/scala/android/ui/akkasimon/Layout.scala:79: not found: value Id
[error]             .framed(Id.blue, BLUE.toLower) <~ rowStyle,
[error]                     ^
[error] /Users/anony/Desktop/Projects/Scala/scala-android/src/main/scala/com/fortysevendeg/scala/android/ui/akkasimon/Layout.scala:81: exception during macro expansion: 
[error] scala.MatchError: (macroid.FragmentBuilder.apply[com.fortysevendeg.scala.android.ui.akkasimon.fragments.ColorFragment](macroid.Ui.apply[com.fortysevendeg.scala.android.ui.akkasimon.fragments.ColorFragment]%28new com.fortysevendeg.scala.android.ui.akkasimon.fragments.ColorFragment%28%29%29, new android.os.Bundle%28%29)(context, support.this.Fragment.legacyFragment): macroid.FragmentBuilder[com.fortysevendeg.scala.android.ui.akkasimon.fragments.ColorFragment]) (of class scala.reflect.internal.Trees$Typed)
[error]         at macroid.FragmentBuildingMacros.passImpl(FragmentBuilding.scala:92)
[error]             .pass(colorKey -> Color.YELLOW, nameColorKey -> YELLOW.toLower)
[error]                  ^
[error] /Users/anony/Desktop/Projects/Scala/scala-android/src/main/scala/com/fortysevendeg/scala/android/ui/akkasimon/Layout.scala:82: not found: value Id
[error]             .framed(Id.yellow, YELLOW.toLower) <~ rowStyle
[error]                     ^
[error] /Users/anony/Desktop/Projects/Scala/scala-android/src/main/scala/com/fortysevendeg/scala/android/ui/akkasimon/Layout.scala:45: exception during macro expansion: 
[error] scala.MatchError: (macroid.FragmentBuilder.apply[com.fortysevendeg.scala.android.ui.akkasimon.fragments.ComputerFragment](macroid.Ui.apply[com.fortysevendeg.scala.android.ui.akkasimon.fragments.ComputerFragment]%28new com.fortysevendeg.scala.android.ui.akkasimon.fragments.ComputerFragment%28%29%29, new android.os.Bundle%28%29)(context, support.this.Fragment.legacyFragment): macroid.FragmentBuilder[com.fortysevendeg.scala.android.ui.akkasimon.fragments.ComputerFragment]) (of class scala.reflect.internal.Trees$Typed)
[error]         at macroid.FragmentBuildingMacros.passImpl(FragmentBuilding.scala:92)
[error]           pass(nameComputerKey -> COMPUTER.toLower).
[error]               ^
[error] /Users/anony/Desktop/Projects/Scala/scala-android/src/main/scala/com/fortysevendeg/scala/android/ui/akkasimon/Layout.scala:46: not found: value Id
[error]           framed(Id.computer, COMPUTER.toLower),
[error]                  ^
[error] /Users/anony/Desktop/Projects/Scala/scala-android/src/main/scala/com/fortysevendeg/scala/android/ui/akkasimon/AkkaSimonActivity.scala:62: value <~ is not a member of Option[android.widget.TextView]
[error]     rounds <~ tvText(getString(R.string.simon_round_counter, roundCounter.toString))
[error]            ^
[error] /Users/anony/Desktop/Projects/Scala/scala-android/src/main/scala/com/fortysevendeg/scala/android/ui/akkasimon/AkkaSimonActivity.scala:67: value <~ is not a member of Option[android.widget.TextView]
[error]     rounds <~ tvText(getString(R.string.simon_round_counter, roundCounter.toString))
[error]            ^
[error] /Users/anony/Desktop/Projects/Scala/scala-android/src/main/scala/com/fortysevendeg/scala/android/ui/akkasimon/fragments/ColorFragment.scala:31: not found: value getUi
[error]   override def onCreateView(inflater: LayoutInflater, container: ViewGroup, savedInstanceState: Bundle) = getUi {
[error]                                                                                                           ^
[error] /Users/anony/Desktop/Projects/Scala/scala-android/src/main/scala/com/fortysevendeg/scala/android/ui/apirequest/Layout.scala:11: object IdGeneration is not a member of package macroid
[error] import macroid.{ActivityContextWrapper, ContextWrapper, FragmentManagerContext, IdGeneration}
[error]        ^
....

Thanks for your help.

**Comment by wpoosanguansit** [comment]
Just found out that M5 has breaking changes.
